SITE:
    Local: '127.0.0.1:8888'
    Remote:
        Url: 'http://roblib_2022.lndo.site'
        Path: user
PORT: 8000
BSREWRITE:
    Css:
        Match: "/themes/custom/roblib_d9/css/"
        Replace: "/css/"
    Js:
        Match: "/themes/custom/roblib_d9/js/"
        Replace: "/js/"
PATHS:
    Watch:
      #changes in these compiled files trigged reload
      - ./css/*.css
      - ./js/*.js
    Scss:
        Dir: ./css/src
        Libraries:
            - libraries/guff
            - bower_components/foundation-sites/scss
            - bower_components/motion-ui/src
            - node_modules/modularscale-sass/stylesheets
            - libraries/fontawesome-free/scss
    Css:
        Dir: css
        #FileName: app.css
    Js:
        Src: ./js/src/*.js
        Dest: js
        FileName: 'ia-islandimagined.behaviors.js'
    Img:
        Src: img/src
        Dest: img

